name: 'Cloud Run'
description: 'Authenticate with gcloud, push image to GCR and deploy as a new revision to Cloud Run'
author: 'David Stefan <stefda@gmail.com>'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  image:
    description: 'Name of the docker image'
    required: true
  service:
    description: 'Name of the service in Cloud Run'
    required: true
  project:
    description: 'GCP project'
    required: true
  region:
    description: 'GCP region'
    required: true
  memory:
    description: 'Memory size'
    required: false
  concurrency:
    description: 'Concurrency count'
    required: false
  allow_unauth:
    description: 'Allow public access to service, true or false'
    required: false
  service key:
    description: 'GCP service key with storage and run permissions'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
